[profile.default]
src = "src"
out = "out"
test = "test"
libs = ["lib"]
[rpc_endpoints]
localhost = "http://localhost:8545"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

