name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3  # Ensure v3 is used
    - name: Use Node.js
      uses: actions/setup-node@v3  # Ensure v3 is used
      with:
        node-version: '16'  # You can set to '16' or '20' for future compatibility
    - run: npm ci
    - run: npm run build
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./frontend/build
